//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHGraduationWarning.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SHGraduationWarning.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;更新學期科目級別資訊&quot;&gt;
        ///	&lt;DuplicateDetection&gt;
        ///		&lt;Detector Name=&quot;更新學期科目級別資訊唯一值&quot;&gt;
        ///			&lt;Field Name=&quot;學生系統編號&quot; /&gt;
        ///			&lt;Field Name=&quot;學年度&quot; /&gt;
        ///			&lt;Field Name=&quot;學期&quot; /&gt;
        ///			&lt;Field Name=&quot;成績年級&quot; /&gt;
        ///			&lt;Field Name=&quot;科目名稱&quot; /&gt;
        ///			&lt;Field Name=&quot;科目級別&quot; /&gt;
        ///		&lt;/Detector&gt;
        ///	&lt;/DuplicateDetection&gt;
        ///	&lt;FieldList&gt;
        ///		&lt;Field Required=&quot;True&quot; Name=&quot;學生系統編號&quot;&gt;
        ///			&lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學生系統編號」不允許空白。&quot; ErrorType=&quot;Er [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportUpdateSubjectLevelVal {
            get {
                return ResourceManager.GetString("ImportUpdateSubjectLevelVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 學期成績匯入檔樣板 {
            get {
                object obj = ResourceManager.GetObject("學期成績匯入檔樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 學期成績匯入檔樣板1 {
            get {
                object obj = ResourceManager.GetObject("學期成績匯入檔樣板1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 學期成績與課規比對樣板 {
            get {
                object obj = ResourceManager.GetObject("學期成績與課規比對樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 學生學期科目與課規課程代碼差異樣板 {
            get {
                object obj = ResourceManager.GetObject("學生學期科目與課規課程代碼差異樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 普通高中個人畢業預警通知書樣板 {
            get {
                object obj = ResourceManager.GetObject("普通高中個人畢業預警通知書樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 班級預警報表樣板 {
            get {
                object obj = ResourceManager.GetObject("班級預警報表樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 畢業審查學生清單樣板 {
            get {
                object obj = ResourceManager.GetObject("畢業審查學生清單樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 畢業預警報表樣板_職業類科預設樣板_ {
            get {
                object obj = ResourceManager.GetObject("畢業預警報表樣板_職業類科預設樣板_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 畢業預警
        ///本功能依學生成績計算規則中的畢業成績計算規則進行畢業預警作業。
        ///目的：確認學生是否符合畢業資格。
        ///請依「年級」、「科別」、「班級」選取欲進行檢查之學生，待檢查完畢後，您可利用「產生報表」功能查看檢核結果。
        ///
        ///報表說明：
        ///「匯出清單」：可直接產出畢業審查結果。
        ///「產生班級報表」：依班級產生班級報表。
        ///「產生報表」：可選取單/多筆學生產生個人報表。.
        /// </summary>
        internal static string 畢業預警說明 {
            get {
                return ResourceManager.GetString("畢業預警說明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 畢業預警通知單合併欄位總表 {
            get {
                object obj = ResourceManager.GetObject("畢業預警通知單合併欄位總表", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 課程與課規比對樣板 {
            get {
                object obj = ResourceManager.GetObject("課程與課規比對樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料合理性檢查(科目屬性)
        ///本功能依學生學期科目成績及採用課程規劃進行資料合理性檢查。
        ///目的：確認學生修習科目屬性是否正確。
        ///請依「年級」、「科別」、「班級」選取欲進行檢查之學生，待檢查完畢後，您可利用「產生報表」功能查看檢核結果。
        ///
        ///工作表說明：
        ///「學期科目成績匯入檔」：若有差異，可直接用匯入學期科目成績功能匯入修改。.
        /// </summary>
        internal static string 資料合理性檢查_科目屬性_ {
            get {
                return ResourceManager.GetString("資料合理性檢查_科目屬性_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料合理性檢查(科目級別)
        ///本功能依學生學期科目成績及採用課程規劃進行資料合理性檢查。
        ///目的：確認學生修習科目級別是否正確。
        ///請依「年級」、「科別」、「班級」選取欲進行檢查之學生，待檢查完畢後，您可利用「產生報表」功能查看檢核結果。
        ///
        ///工作表說明：
        ///「依學期成績為主比對課規不符合」：學生學期導目成績中，若科目級別與課程規劃不一致，則「新科目級別」欄位顯示課規上所規範之科目級別。
        ///「依課規為主比對學期成績不符合」：課程規劃之課程，但學生無成績記錄之科目。
        ///「依課規比對課程群組學分總數不符合」.
        /// </summary>
        internal static string 資料合理性檢查_科目級別_ {
            get {
                return ResourceManager.GetString("資料合理性檢查_科目級別_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料合理性檢查(課程科目級別)
        ///本功能依學生修課記錄及採用課程規劃進行資料合理性檢查。
        ///目的：確認開課及課程規劃表是否一致。
        ///檢查學生狀態：一般生、延修生。
        ///請依「年級」、「科別」、「班級」選取欲進行檢查之學生，待檢查完畢後，您可利用「產生報表」功能查看檢核結果。
        ///
        ///工作表說明：
        ///「依課程為主比對課規不符合」：所開設之課程不在課程規劃中。
        ///「依課規為主比對課程不符合」：課程規劃之課程查無開設記錄。.
        /// </summary>
        internal static string 資料合理性檢查_課程科目級別_ {
            get {
                return ResourceManager.GetString("資料合理性檢查_課程科目級別_", resourceCulture);
            }
        }
    }
}
