//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHStudentStatus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SHStudentStatus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;異動代號對照表&gt;
        ///	&lt;異動&gt;
        ///		&lt;代號&gt;001&lt;/代號&gt;
        ///		&lt;原因及事項&gt;持國民中學畢業證書者(含國中補校)&lt;/原因及事項&gt;
        ///		&lt;分類&gt;新生異動&lt;/分類&gt;
        ///	&lt;/異動&gt;
        ///	&lt;異動&gt;
        ///		&lt;代號&gt;002&lt;/代號&gt;
        ///		&lt;原因及事項&gt;持國民中學補習學校資格證明書者&lt;/原因及事項&gt;
        ///		&lt;分類&gt;新生異動&lt;/分類&gt;
        ///	&lt;/異動&gt;
        ///	&lt;異動&gt;
        ///		&lt;代號&gt;003&lt;/代號&gt;
        ///		&lt;原因及事項&gt;持國民中學補習學校結(修)業證明書者&lt;/原因及事項&gt;
        ///		&lt;分類&gt;新生異動&lt;/分類&gt;
        ///	&lt;/異動&gt;
        ///	&lt;異動&gt;
        ///		&lt;代號&gt;004&lt;/代號&gt;
        ///		&lt;原因及事項&gt;持國民中學修業證明書者(修習三年級課程)&lt;/原因及事項&gt;
        ///		&lt;分類&gt;新生異動&lt;/分類&gt;
        ///	&lt;/異動&gt;
        ///	&lt;異動&gt;
        ///		&lt;代號&gt;005&lt;/代號&gt;
        ///		&lt;原因及事項&gt;持國民中學畢業程度學力鑑定考試及格證明書者&lt;/原因及事項&gt;
        ///		&lt;分類&gt;新生異動&lt;/分類&gt;
        ///	&lt;/異動&gt;
        ///	&lt;異動&gt;
        ///		&lt;代號&gt;006&lt;/代號&gt;
        ///		&lt;原因及事項&gt;回國僑 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateCode_SH {
            get {
                return ResourceManager.GetString("UpdateCode_SH", resourceCulture);
            }
        }
    }
}
